title: Configure OpenShift Cluster on OCI - v1.0.0
description: Post-installation configuration for OpenShift clusters on OCI, including image registry setup
schemaVersion: 1.0.0
version: "20250126"
locale: "en"

variableGroups:
- title: "Cluster Access"
  variables:
  - kubeconfig_content

- title: "Cluster Information"
  variables:
  - compartment_ocid

- title: "Image Registry Configuration"
  variables:
  - image_registry_storage_class
  - image_registry_storage_size

- title: "TLS Certificate Configuration"
  variables:
  - dns_zone_name
  - letsencrypt_email


###########
# VARIABLES
###########
variables:
  kubeconfig_par_url:
    type: string
    title: Kubeconfig PAR URL
    description: Upload your kubeconfig to OCI Object Storage and create a Pre-Authenticated Request (PAR) URL. Paste the PAR URL here. The kubeconfig will be fetched securely from Object Storage.
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: Compartment
    description: Compartment OCID where the OpenShift cluster and DNS zone exist.
    required: true

  image_registry_storage_class:
    type: string
    title: Image Registry Storage Class
    description: StorageClass to use for the image registry PVC. Use oci-bv-immediate for single-replica setup.
    default: "oci-bv-immediate"
    required: true

  image_registry_storage_size:
    type: string
    title: Image Registry Storage Size
    description: Size of persistent volume for image registry (e.g., 100Gi, 200Gi, 500Gi)
    default: "100Gi"
    required: true

  dns_zone_name:
    type: string
    title: DNS Zone Name
    description: "OCI DNS zone name for TLS certificates (e.g., oracle.maxiron.cloud). Leave empty to skip TLS certificate setup and use self-signed certificates."
    required: false

  letsencrypt_email:
    type: string
    title: Let's Encrypt Email
    description: Email address for Let's Encrypt account registration and certificate expiry notifications. Defaults to cloud@maxiron.com.
    default: "cloud@maxiron.com"
    required: false


